server:
  port: 8002

spring:
  application:
    name: carer-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/carer_db
    username: carer_user
    password: carer_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: |
          NewCarer:com.healthcare.staffing.shared.events.carer.NewCarer,
          CarerUpdated:com.healthcare.staffing.shared.events.carer.CarerUpdated,
          CarerAvailabilityChanged:com.healthcare.staffing.shared.events.carer.CarerAvailabilityChanged

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.healthcare.staffing: DEBUG
    org.springframework.kafka: INFO
